version: "3"

services:
  api:
    image: exatom42/programtan:latest
    restart: always
    ports:
      - "3000:80"

  db:
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
